apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: class-cluster
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: t3.large
    desiredCapacity: 2
  # - name: ng-2
  #   instanceType: t2.micro
  #   desiredCapacity: 2
