apiVersion: apps/v1
kind: Deployment
metadata:
  name: class-juiceapp
  labels:
    app: juiceapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juiceapp
  template:
    metadata:
      labels:
        app: juiceapp
    spec:
      containers:
        - name: juiceapp
          image: bkimminich/juice-shop
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: class-juiceapp-service
spec:
  type: NodePort
  selector:
    app: juiceapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30106
